# Generated by Django 3.2 on 2023-04-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'db_table': 'tbl_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('modalidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('modalidad_descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'db_table': 'tbl_modalidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('nivel_id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'db_table': 'tbl_nivel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('oferta_id', models.AutoField(primary_key=True, serialize=False)),
                ('oferta_titulo', models.CharField(max_length=255)),
                ('oferta_fec_pub', models.DateField()),
                ('oferta_fec_fin', models.DateField()),
                ('oferta_resumen', models.TextField(blank=True, null=True)),
                ('oferta_detalle', models.TextField(blank=True, null=True)),
                ('oferta_estado', models.IntegerField()),
                ('oferta_fecreg', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_oferta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfertaPostulante',
            fields=[
                ('oferta_postulante_id', models.AutoField(primary_key=True, serialize=False)),
                ('oferta_postulante_fecreg', models.DateTimeField()),
                ('oferta_postulante_estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tbl_oferta_postulante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('periodo_id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'db_table': 'tbl_periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('postulante_id', models.AutoField(primary_key=True, serialize=False)),
                ('postulante_nombres', models.CharField(max_length=255)),
                ('postulante_apellidos', models.CharField(max_length=255)),
                ('postulante_nrodocide', models.CharField(max_length=100)),
                ('postulante_fecnac', models.DateField()),
                ('postulante_genero', models.CharField(max_length=1)),
                ('postulante_estado', models.CharField(max_length=1)),
                ('postulante_fecreg', models.DateTimeField()),
                ('postulante_perfil', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_postulante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostulanteContacto',
            fields=[
                ('postulante_contacto_id', models.AutoField(primary_key=True, serialize=False)),
                ('postulante_contacto_valor', models.CharField(max_length=255)),
                ('postulante_contacto_estado', models.CharField(max_length=1)),
                ('postulante_contacto_fecreg', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_postulante_contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostulanteEstudio',
            fields=[
                ('postulante_estudio_id', models.AutoField(primary_key=True, serialize=False)),
                ('postulante_estudio_titulo', models.CharField(max_length=255)),
                ('postulante_estudio_institucion', models.CharField(max_length=255)),
                ('postulante_estudio_fecini', models.DateField()),
                ('postulante_estudio_fecfin', models.DateField(blank=True, null=True)),
                ('postulante_estudio_estado', models.CharField(max_length=1)),
                ('postulante_estudio_fecreg', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_postulante_estudio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostulanteExperiencia',
            fields=[
                ('postulante_experiencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('postulante_experiencia_puesto', models.CharField(max_length=255)),
                ('postulante_experiencia_empresa', models.CharField(max_length=255)),
                ('postulante_experiencia_detalle', models.TextField()),
                ('postulante_experiencia_fecini', models.DateField()),
                ('postulante_experiencia_fecfin', models.DateField(blank=True, null=True)),
                ('postulante_experiencia_estado', models.CharField(max_length=1)),
                ('postulante_experiencia_fecreg', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_postulante_experiencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoContacto',
            fields=[
                ('tipo_contacto_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contacto_descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
            options={
                'db_table': 'tbl_tipo_contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEstudio',
            fields=[
                ('tipo_estudio_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_estudio_descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
            options={
                'db_table': 'tbl_tipo_estudio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('ubicacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion_pais', models.CharField(max_length=255, verbose_name='Pais')),
                ('ubicacion_ciudad', models.CharField(max_length=255, verbose_name='Ciudad')),
                ('ubicacion_codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo')),
            ],
            options={
                'db_table': 'tbl_ubicacion',
                'managed': False,
            },
        ),
    ]
